In [1]:
from tensorflow.keras.preprocessing import image

In [2]:
img = image.load_img('test_img.jpeg', target_size=(224, 224))

In [3]:
img_array = image.img_to_array(img)

In [4]:
# this cell is done so that the image shape is fit for model (accpets batches of images instead of single image)
import numpy as np
expanded_img_array = np.expand_dims(img_array, axis=0)
print(expanded_img_array.shape)

(1, 224, 224, 3)


In [5]:
import tensorflow as tf
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input

In [6]:
model = ResNet50(weights='imagenet',
                 include_top=False,
                 input_shape=(224, 224, 3))

model.trainable = False #fix weights

model = tf.keras.Sequential([
    model,
    GlobalMaxPooling2D()
])

In [ ]:
preprocessed_img = preprocess_input(expanded_img_array) #reordering rgb to bgr and other preprocessing for imagenet
print(preprocessed_img.shape)
preprocessed_img

(1, 224, 224, 3)


array([[[[120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         ...,
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ]],

        [[120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         ...,
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ]],

        [[120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         ...,
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ]],

        ...,

        [[120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         ...,
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ],
         [120.061, 107.221, 100.32 ]],

        [[

In [ ]:
model.predict(preprocessed_img)

array([[ 5.3759236, 25.702105 ,  2.5506554, ...,  5.2237244,  7.4053173,
        14.645377 ]], dtype=float32)

In [11]:
from numpy.linalg import norm

model.predict(preprocessed_img).flatten()/norm(model.predict(preprocessed_img).flatten())

array([0.0193399 , 0.09246339, 0.00917599, ..., 0.01879236, 0.02664065,
       0.05268678], dtype=float32)